# config_gpu.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-standard-8  # Ensure this machine type is compatible with GPUs
        acceleratorType: NVIDIA_TESLA_P100  # GPU type (ensure this matches your quota)
        acceleratorCount: 1  # Number of GPUs
    replicaCount: 1
    containerSpec:
        imageUri: europe-west1-docker.pkg.dev/cleaninbox-448011/container-registry/train.image:latest
        env:
        - name: WANDB_API_KEY
          value: $WANDB_API_KEY
        - name: WANDB_PROJECT
          value: cleaninbox
        - name: WANDB_ENTITY
          value: cleaninbox
        args:
        - "++environment.log_wandb=True"
        - "++experiment.experiment_description.name=8k40eGPU"

