# config_cpu.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-8
    replicaCount: 2
    containerSpec:
        imageUri: europe-west1-docker.pkg.dev/cleaninbox-448011/container-registry/train.image:latest
        env:
        - name: WANDB_API_KEY
          value: $WANDB_API_KEY
        - name: WANDB_PROJECT
          value: cleaninbox
        - name: WANDB_ENTITY
          value: cleaninbox
          # add the following for passing overriding args to the hydra cfg 
        args:
        - "++environment.log_wandb=True"
          
retryConfig:
    maxRetryCount: 0
    
scheduling:
    timeout: 60000s  #
    restartJobOnWorkerRestart: true
        
