#config.yaml
hydra:
  job: 
    chdir: True
    
model:
  name: "huawei-noah/TinyBERT_General_4L_312D"
  
dataset:
  name: "PolyAI/banking77"
  classes: 77
  
defaults:
    - experiment: exp1
    
  
 
    

  
