#config.yaml
hydra:
  job:
    chdir: True

model:
  name: "huawei-noah/TinyBERT_General_4L_312D"
  save_model: False

dataset:
  name: "PolyAI/banking77"
  num_labels: 77
  val_size: 0.2
  num_train_samples: 10003
  num_test_samples: 3080

basic:
  raw_path: "./data/raw/"
  proc_path: "./data/processed/"
  models: "./models/"
  train: False

unittest:
  data:

  model:
    input_size: 128

  train:
    epochs: 1
    batch_size: 16
    lr: 1e-3
    seed: 42

defaults:
    - experiment: overfit
    - optimizer: adam





