#config.yaml
hydra:
  job:
    chdir: True

model:
  name: "huawei-noah/TinyBERT_General_4L_312D"
  save_model: True

dataset:
  name: "PolyAI/banking77"
  num_labels: 77
  val_size: 0
  num_train_samples: 10003
  num_test_samples: 3080

basic:
  raw_path: "./data/raw/"
  proc_path: "./data/processed/"
  proc_banking_data: "${basic.proc_path}banking77/"
  models: "./models/"
  model_ckpt: "${basic.models}model.pth"

gs:
  bucket: "banking77"
  data: "data/"
  raw_data: "${gs.data}raw/banking77/"
  proc_data: "${gs.data}processed/banking77/"
  model: "models"
  model_ckpt: "${gs.model}/model_current.pth"
  monitoring: "monitoring/"
  monitoring_db: "${gs.monitoring}newdata_predictions_db.csv"
  # backend_url: "https://backend-170780472924.europe-west1.run.app"
  backend_url: "http://127.0.0.1:8000"

environment:
  log_wandb: True
  run_in_cloud: True
  models: "models/"
  model_ckpt: "${gs.model}/model_current.pth"

mount_gs:
  bucket: "/gcs/${gs.bucket}/"
  data: "${mount_gs.bucket}data/"
  raw_data: "${mount_gs.data}raw/banking77/"
  proc_data: "${mount_gs.data}processed/banking77/"
  models: "${mount_gs.bucket}models/"
  model_ckpt: "${mount_gs.models}model_current.pth"


defaults:
    - experiment: semifit
    - optimizer: adam
