#config.yaml
hydra:
  job: 
    chdir: True
    
model:
  name: "huawei-noah/TinyBERT_General_4L_312D"

dataset:
  name: "PolyAI/banking77"
  num_labels: 77

basic:
  raw_path: "./data/raw/"
  proc_path: "./data/processed/"
  models: "./models/"
  train: false

defaults:
    - experiment: overfit
    

 
    

  
