#config.yaml
hydra:
  job: 
    chdir: True
    
model:
  name: "huawei-noah/TinyBERT_General_4L_312D"
  save_model: True

dataset:
  name: "PolyAI/banking77"
  num_labels: 77
  val_size: 0.2
  num_train_samples: 10003
  num_test_samples: 3080

basic:
  raw_path: "./data/raw/"
  proc_path: "./data/processed/"
  proc_banking_data: "${proc_path}banking77/"
  models: "./models/"
  train: False
  
environment: 
  log_wandb: False
  run_in_cloud: True
  model_ckpt: "${models}model.pth"

defaults:
    - experiment: overfit
    

 
    

  
