name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    permissions:
     contents: 'read'
     id-token: 'write'
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r requirements.txt
          pip install -r requirements_test.txt
          pip install -e .
          pip install google-cloud-storage google-cloud-aiplatform torch
          pip list

      # Authenticate using workload identity pools
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'cleaninbox-448011'
          workload_identity_provider: projects/170780472924/locations/global/workloadIdentityPools/github/providers/my-repo
          service_account: 'dvc-ci@cleaninbox-448011.iam.gserviceaccount.com'

      # Download data
      - name: Pull data with DVC
        run: |
          dvc pull data

      # Debug dvc data folder error
      - name: Debug missing data folder
        run: |
          pwd
          ls -laR data


      # Run tests
      - name: Run tests & coverage
        run: |
          coverage run -m pytest tests/ && coverage report
